--USE master
--DROP DATABASE QUANLYBANTHUOC

CREATE DATABASE QUANLYBANTHUOC

GO
USE QUANLYBANTHUOC
GO

CREATE TABLE NhaCungCap (
	MaNhaCungCap INT PRIMARY KEY IDENTITY (1, 1),
	TenNhaCungCap NVARCHAR(60) NOT NULL,
	SoDienThoai VARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	QuocGia NVARCHAR(100) DEFAULT 'Việt Nam'
);

GO
CREATE TABLE NhomThuoc (
	MaNhomThuoc INT PRIMARY KEY IDENTITY (1, 1),
	TenNhomThuoc NVARCHAR(100) NOT NULL
);

GO
CREATE TABLE Quay (
	MaQuay INT PRIMARY KEY IDENTITY (1, 1),
	TenQuay NVARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(255) NOT NULL,
	Phuong NVARCHAR(50) NOT NULL,
	ThanhPho NVARCHAR(50) NOT NULL,
	Tinh NVARCHAR(25) NOT NULL,
);

GO
CREATE TABLE KhachHang (
	MaKhachHang INT PRIMARY KEY IDENTITY (1, 1),
	TenKhachHang NVARCHAR(100) NOT NULL,
	SoDienThoai VARCHAR(10) NOT NULL,
	NgayTao DATE NOT NULL
) 

GO 


GO
CREATE TABLE NhanVien (
	MaNhanVien INT PRIMARY KEY IDENTITY (1, 1),
	TenNhanVien NVARCHAR(50) NOT NULL,
	NgayVaoLam DATE NOT NULL,
	CaLamViec NVARCHAR(10) NOT NULL,
	SoDienThoai VARCHAR(10) NOT NULL,
	MatKhau VARCHAR(18) NOT NULL,
	MaQuay INT FOREIGN KEY REFERENCES Quay(MaQuay),
	ChucVu VARCHAR(10) NOT NULL,

)

GO
CREATE TABLE Thuoc (
	MaThuoc INT PRIMARY KEY IDENTITY (1, 1),
	TenThuoc NVARCHAR(100) NOT NULL,
	MaNhaCungCap INT FOREIGN KEY REFERENCES NhaCungCap(MaNhaCungCap),
	DonViTinh NVARCHAR (25) NOT NULL,
	ThanhPhanChinh NVARCHAR(100),
	DonViTinhLe NVARCHAR(25) NOT NULL,
	HanSuDung DATE,
	DieuKienBaoQuan NVARCHAR(255), 
	DonViTinhChan NVARCHAR (25) NOT NULL,
	GhiChu NVARCHAR(255),
	GiaNhapLe REAL NOT NULL,
	GiaNhapChan REAL NOT NULL,
	GiaBanLe REAL NOT NULL,
	GiaBanChan REAL NOT NULL,
	MaNhomThuoc INT FOREIGN KEY REFERENCES NhomThuoc(MaNhomThuoc),
	MaGiamGia INT FOREIGN KEY REFERENCES MaGiamGia(MaGiamGia)
)

GO
CREATE TABLE Kho (
	SoLuong INT NOT NULL,
	MaThuoc INT FOREIGN KEY REFERENCES Thuoc(MaThuoc)
);

GO
CREATE TABLE HoaDon (
	MaHoaDon INT PRIMARY KEY IDENTITY (1, 1),
	NgayLapHoaDon Date NOT NULL,
	TrangThai NVARCHAR(10) NOT NULL,
	PhuongThucThanhToan NVARCHAR(10) DEFAULT 'Tiền mặt',
	TienNhan REAL NOT NULL,
	TienDu REAL DEFAULT 0,
	MaKhachHang INT FOREIGN KEY REFERENCES KhachHang(MaKhachHang),
	MaNhanVien INT FOREIGN KEY REFERENCES NhanVien(MaNhanVien),
	MaQuay INT FOREIGN KEY REFERENCES Quay(MaQuay),
	TongTienGiam REAL DEFAULT 0,
	TongTien REAL NOT NULL
)

GO
CREATE TABLE MaGiamGia (
	MaGiamGia INT PRIMARY KEY IDENTITY (1, 1),
	NgayBatDau DATE NOT NULL,
	NgayKetThuc DATE NOT NULL,
	PhanTramGiamGia REAL DEFAULT 0.05,
	MoTa NVARCHAR(255)
)

GO
CREATE TABLE ChiTietHoaDon (
	MaChiTietHoaDon INT PRIMARY KEY IDENTITY (1, 1),
	SoLuong INT NOT NULL,
	DonViTinh NVARCHAR(10) NOT NULL,
	DonGia REAL NOT NULL,
	MaSanPham INT FOREIGN KEY REFERENCES Thuoc(MaThuoc),
	Thue REAL,
	ThanhTien REAL NOT NULL,
	GiamGia REAL DEFAULT 0,
	MaHoaDon INT FOREIGN KEY REFERENCES HoaDon(MaHoaDon),
	MaGiamGia INT FOREIGN KEY REFERENCES MaGiamGia(MaGiamGia)
)

